apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 3  # You can adjust the number of replicas as needed.
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd:2-alpine  # Use the official Apache image.
        ports:
        - containerPort: 80
